# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BadmintonStats' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BadmintonStats
  pod 'SwiftDate'
  pod 'RealmSwift'
  pod 'RxSwift'
  pod 'ObjectMapper'
  pod 'Cartography'

  target 'BadmintonStatsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BadmintonStatsUITests' do
    # Pods for testing
  end

end
